In [1]:
from pathlib import Path
import json
import pandas as pd

In [2]:
Path.cwd()

PosixPath('data')

In [6]:
sorted(p.name for p in Path.cwd().iterdir())

['.DS_Store',
 '.ipynb_checkpoints',
 'LINCS_small_molecules.tsv',
 'descriptor_summary_statistics.csv',
 'drug_master.json',
 'example_morgan_fingerprints.csv',
 'fingerprint_similarity_correlations.csv',
 'fingerprint_similarity_pairwise_sample.csv',
 'fingerprint_similarity_summary.csv',
 'lincs_morgan_fingerprints_2048.npy',
 'lincs_small_molecules_valid_unique.tsv',
 'morgan_autoencoder_bottleneck_sweep_results.csv',
 'morgan_autoencoder_latent15.csv',
 'morgan_autoencoder_latent15_umap.csv',
 'morgan_autoencoder_latent64_vectors.csv',
 'morgan_full_50_epoch_bottleneck_summary.csv',
 'morgan_full_50_epoch_loss_curves.csv',
 'morgan_to_maccs_latent32_results_summary.csv',
 'morgan_to_maccs_summary.md',
 'objective_3_lincs_morgan_autoencoder.ipynb',
 'part4_predicting.ipynb',
 'pca_cactvs_pubchem_fingerprints.csv',
 'pca_maccs_keys.csv',
 'pca_molecular_descriptors.csv',
 'pca_morgan_fingerprints.csv',
 'perturbseqr_cactvs_pubchem_fingerprints.csv',
 'perturbseqr_maccs_keys.csv',
 'perturbseqr_metadata',
 'perturbseqr_molecular_descriptors.csv',
 'perturbseqr_morgan_fingerprints.csv',
 'representation_comparison_summary.csv',
 'tsne',
 'umap_cactvs_pubchem_fingerprints.csv',
 'umap_combined_features',
 'umap_maccs_keys.csv',
 'umap_metals',
 'umap_molecular_descriptors.csv',
 'umap_morgan_fingerprints.csv',
 'umap_rings']

In [7]:
drug_master_path = Path.cwd() / "drug_master.json"

with open(drug_master_path, "r") as f:
    drug_master = json.load(f)

type(drug_master), len(drug_master)

(dict, 6801)

In [8]:
first_key = next(iter(drug_master))
first_key, drug_master[first_key]

('be-2254',
 {'name': 'be-2254',
  'pubchem_cid': '86308637',
  'inchi_key': 'PZZOEXPDTYIBPI-MRXNPFEDSA-N',
  'smiles': 'Oc1ccc(CCNC[C@H]2CCc3ccccc3C2=O)cc1 |r|',
  'broad_id': 'BRD-A24429032-003-03-2',
  'moa': 'adrenergic receptor antagonist',
  'target': 'ADRA1A',
  'clinical_phase': 'Phase 2',
  'disease_area': '',
  'indication': '',
  'fda_approved': False})

In [10]:
drug_master_df = pd.DataFrame.from_dict(drug_master, orient="index")
drug_master_df.index.name = "perturbseqr_drug_id"

print(drug_master_df.shape)
print(drug_master_df.columns.tolist())

drug_master_df[
    ["name", "smiles", "broad_id", "pubchem_cid", "inchi_key", "target", "moa"]
].isna().sum().sort_values()

(6801, 11)
['name', 'pubchem_cid', 'inchi_key', 'smiles', 'broad_id', 'moa', 'target', 'clinical_phase', 'disease_area', 'indication', 'fda_approved']

name           0
smiles         0
broad_id       0
pubchem_cid    0
inchi_key      0
target         0
moa            0
dtype: int64

In [11]:
print("Unique Broad IDs:", drug_master_df["broad_id"].nunique())
print("Duplicate Broad IDs:", drug_master_df["broad_id"].duplicated().sum())

drug_master_df["broad_id"].value_counts().head(10)

Unique Broad IDs: 6777
Duplicate Broad IDs: 24

broad_id
                          25
BRD-A24429032-003-03-2     1
BRD-K62971431-001-01-9     1
BRD-K00003374-001-01-9     1
BRD-A66419424-001-02-4     1
BRD-K75527158-360-05-6     1
BRD-K20738689-001-01-2     1
BRD-K06753942-001-14-5     1
BRD-K00003398-001-01-9     1
BRD-K00003291-001-01-9     1
Name: count, dtype: int64

In [12]:
duplicate_broad_ids = (
    drug_master_df["broad_id"]
    .value_counts()
    .loc[lambda s: s > 1]
)

duplicate_broad_ids

broad_id
    25
Name: count, dtype: int64

In [13]:
shared_broad_id = duplicate_broad_ids.index[0]

drug_master_df.loc[
    drug_master_df["broad_id"] == shared_broad_id,
    ["name", "smiles", "broad_id", "pubchem_cid", "moa", "target"]
]

,name,smiles,broad_id,pubchem_cid,moa,target
perturbseqr_drug_id,,,,,,
terreic-acid-(-),terreic-acid-(-),,,,Bruton's tyrosine kinase (BTK) inhibitor,BTK
elactocin,elactocin,,,,exportin antagonist,XPO1
homochlorcyclizine,homochlorcyclizine,,,,antihistamine,HRH1
lcz696,lcz696,,,,angiotensin receptor antagonist,
fluorometholone,fluorometholone,,,,glucocorticoid receptor agonist,NR3C1
merck60,merck60,,,,HDAC inhibitor,HDAC1|HDAC2
diflorasone-diacetate,diflorasone-diacetate,,,,glucocorticoid receptor agonist,NR3C1
fpa-124,fpa-124,,,,AKT inhibitor,
rs-0481,rs-0481,,,,immunostimulant,
estramustine,estramustine,,,,DNA alkylating agent,ESR1|ESR2|MAP1A|MAP2
nadph,nadph,,,,,DRD2|DRD3|DRD4|GHSR|HTR2A|HTR2C
bntx,bntx,,,,opioid receptor antagonist,OPRD1|OPRK1|OPRM1
sep-227900,sep-227900,,,,D-amino acid oxidase Inhibitor,DAO
doxorubicin,doxorubicin,,,,topoisomerase inhibitor,TOP2A
pinitol,pinitol,,,,gamma secretase inhibitor,
apr-246,apr-246,,,,p53 activator,TP53
t-025,t-025,,,,CLK inhibitor,
nov-002,nov-002,,,,,GSR
s-nitrosoglutathione,s-nitrosoglutathione,,,,nitric oxide stimulant,PTPN1
sb-218078,sb-218078,,,,CHK inhibitor,CHEK1
cloperastine-fendizoate,cloperastine-fendizoate,,,,potassium channel antagonist,
nisin,nisin,,,,bacterial cell wall synthesis inhibitor,
pipecuronium,pipecuronium,,,,neuromuscular blocker,CHRM2|CHRM3|CHRNA2
dimenhydrinate,dimenhydrinate,,,,histamine receptor antagonist,HRH1
vilanterol,vilanterol,,,,adrenergic receptor agonist,ADRB2

In [14]:
consensus_path = Path.cwd() / "cp_mean_coeff_mat.tsv.gz"

consensus_path.exists(), consensus_path.stat().st_size / 1e9

(True, 1.897525732)

In [15]:
preview = pd.read_csv(
    consensus_path,
    sep="\t",
    compression="gzip",
    nrows=5
)

preview.shape

(5, 12328)

In [16]:
preview.iloc[:, :8]

,Unnamed: 0,A1CF,A2M,A4GALT,A4GNT,AAAS,AACS,AADAC
0,afatinib,0.001353,-0.002113,-0.000360,0.000507,-0.000123,0.000799,-0.001517
1,erlotinib,0.000755,-0.000268,-0.000690,0.000107,0.000050,-0.000775,-0.000117
2,neratinib,0.000463,-0.003915,-0.000118,0.000174,-0.000900,0.000787,-0.001803
3,lapatinib,-0.000138,0.000255,0.000192,-0.000241,0.000348,0.000737,0.000374
4,pazopanib,-0.000276,0.000854,-0.000363,-0.000167,-0.000008,-0.001390,-0.000128

In [17]:
print("Number of gene columns:", preview.shape[1] - 1)
print("First column name:", preview.columns[0])
print("First five compound names:")
print(preview.iloc[:, 0].tolist())

Number of gene columns: 12327
First column name: Unnamed: 0
First five compound names:
['afatinib', 'erlotinib', 'neratinib', 'lapatinib', 'pazopanib']

In [18]:
# Read only the compound-name column from the full file
consensus_names = pd.read_csv(
    consensus_path,
    sep="\t",
    compression="gzip",
    usecols=[0]
)

consensus_names.columns = ["signature_name"]

print(consensus_names.shape)
print("Unique signature names:", consensus_names["signature_name"].nunique())
consensus_names.head()

(33609, 1)
Unique signature names: 33608

  signature_name
0       afatinib
1      erlotinib
2      neratinib
3      lapatinib
4      pazopanib

In [19]:
drug_names = set(drug_master_df["name"].str.lower().str.strip())
signature_names = set(consensus_names["signature_name"].str.lower().str.strip())

overlap = drug_names & signature_names

print("Drug-master compounds:", len(drug_names))
print("Consensus signature names:", len(signature_names))
print("Exact name overlap:", len(overlap))

Drug-master compounds: 6801
Consensus signature names: 33609
Exact name overlap: 3154

In [20]:
drug_master_df_clean = (
    drug_master_df
    .reset_index()
    .assign(match_name=lambda df: df["name"].str.lower().str.strip())
)

consensus_names_clean = (
    consensus_names
    .assign(match_name=lambda df: df["signature_name"].str.lower().str.strip())
)

exact_matches = drug_master_df_clean.merge(
    consensus_names_clean,
    on="match_name",
    how="inner"
)

exact_matches.shape

(3154, 14)

In [21]:
exact_matches[
    [
        "perturbseqr_drug_id",
        "name",
        "broad_id",
        "smiles",
        "signature_name",
        "moa",
        "target",
    ]
].head(10)

,perturbseqr_drug_id,name,broad_id,smiles,signature_name,moa,target
0,be-2254,be-2254,BRD-A24429032-003-03-2,Oc1ccc(CCNC[C@H]2CCc3ccccc3C2=O)cc1 |r|,BE-2254,adrenergic receptor antagonist,ADRA1A
1,dazmegrel,dazmegrel,BRD-K20738689-001-01-2,Cc1c(Cn2ccnc2)c2ccccc2n1CCC(O)=O,dazmegrel,thromboxane synthase inhibitor,TBXAS1
2,nobiletin,nobiletin,BRD-K06753942-001-14-5,COc1ccc(cc1OC)-c1cc(=O)c2c(OC)c(OC)c(OC)c(OC)c2o1,nobiletin,MEK inhibitor,MAP2K1
3,l-368899,l-368899,BRD-K00004282-003-01-9,Cc1ccccc1N1CCN(CC1)S(=O)(=O)C[C@]12CC[C@H](C[C...,L-368899,oxytocin receptor antagonist,AVPR1A|AVPR2|OXTR
4,betamethasone-valerate,betamethasone-valerate,BRD-K34032314-001-04-1,CCCCC(=O)O[C@@]1([C@@H](C)C[C@H]2[C@@H]3CCC4=C...,betamethasone-valerate,glucocorticoid receptor agonist,NR3C1
5,pnu-282987,pnu-282987,BRD-K28863208-001-03-8,Clc1ccc(cc1)C(=O)N[C@H]1CN2CCC1CC2,PNU-282987,cholinergic receptor agonist,CHRNA7
6,diclofenac,diclofenac,BRD-K08252256-236-33-8,OC(=O)Cc1ccccc1Nc1c(Cl)cccc1Cl,diclofenac,cyclooxygenase inhibitor,AKR1C3|ALOX5|ASIC1|ASIC3|KCNQ2|KCNQ3|PLA2G2A|P...
7,hemado,hemado,BRD-K34672903-001-02-5,CCCCC#Cc1nc(NC)c2ncn([C@@H]3O[C@H](CO)[C@@H](O...,hemado,adenosine receptor agonist,ADORA1|ADORA2A|ADORA2B|ADORA3
8,proadifen,proadifen,BRD-K46317332-003-16-0,CCCC(C(=O)OCCN(CC)CC)(c1ccccc1)c1ccccc1,proadifen,nitric oxide synthase inhibitor,NOS1
9,simvastatin,simvastatin,BRD-K22134346-001-28-0,CCC(C)(C)C(=O)O[C@H]1C[C@@H](C)C=C2C=C[C@H](C)...,simvastatin,HMGCR inhibitor,HMGCR|ITGB2

In [22]:
exact_matches.to_csv(
    Path.cwd() / "matched_drugmaster_consensus_names.csv",
    index=False
)

print("Saved:", Path.cwd() / "matched_drugmaster_consensus_names.csv")

Saved: data/matched_drugmaster_consensus_names.csv

In [23]:
morgan_preview = pd.read_csv(
    Path.cwd() / "perturbseqr_morgan_fingerprints.csv",
    nrows=3
)

morgan_preview.columns[:10], morgan_preview.shape

(Index(['record_id', 'name', 'pubchem_cid', 'inchi_key', 'smiles', 'broad_id',
        'moa', 'target', 'clinical_phase', 'disease_area'],
       dtype='str'),
 (3, 2060))

In [24]:
morgan_preview.columns[-10:]

Index(['morgan_2038', 'morgan_2039', 'morgan_2040', 'morgan_2041',
       'morgan_2042', 'morgan_2043', 'morgan_2044', 'morgan_2045',
       'morgan_2046', 'morgan_2047'],
      dtype='str')

In [25]:
with open(Path.cwd() / "perturbseqr_morgan_fingerprints.csv", "r") as f:
    header = f.readline().strip().split(",")

print("Total columns:", len(header))
print("First metadata columns:", header[:12])
print("Last fingerprint columns:", header[-10:])

Total columns: 2060
First metadata columns: ['record_id', 'name', 'pubchem_cid', 'inchi_key', 'smiles', 'broad_id', 'moa', 'target', 'clinical_phase', 'disease_area', 'indication', 'fda_approved']
Last fingerprint columns: ['morgan_2038', 'morgan_2039', 'morgan_2040', 'morgan_2041', 'morgan_2042', 'morgan_2043', 'morgan_2044', 'morgan_2045', 'morgan_2046', 'morgan_2047']

In [26]:
# Load just the metadata columns from the full Morgan file
morgan_metadata = pd.read_csv(
    Path.cwd() / "perturbseqr_morgan_fingerprints.csv",
    usecols=[
        "record_id", "name", "pubchem_cid", "inchi_key", "smiles",
        "broad_id", "moa", "target", "clinical_phase",
        "disease_area", "indication", "fda_approved"
    ]
)

morgan_metadata.shape

(6754, 12)

In [27]:
morgan_metadata["match_name"] = morgan_metadata["name"].str.lower().str.strip()

matched_morgan_metadata = morgan_metadata.merge(
    exact_matches[
        ["perturbseqr_drug_id", "match_name", "signature_name"]
    ],
    on="match_name",
    how="inner"
)

matched_morgan_metadata.shape

(3131, 15)

In [28]:
exact_match_ids = set(exact_matches["perturbseqr_drug_id"])
morgan_match_ids = set(matched_morgan_metadata["perturbseqr_drug_id"])

missing_from_morgan = (
    exact_matches[
        ~exact_matches["perturbseqr_drug_id"].isin(morgan_match_ids)
    ][
        ["perturbseqr_drug_id", "name", "smiles", "broad_id", "signature_name"]
    ]
)

print("Exact matches missing from Morgan feature file:", len(missing_from_morgan))
missing_from_morgan.head(20)

Exact matches missing from Morgan feature file: 23

,perturbseqr_drug_id,name,smiles,broad_id,signature_name
299,homochlorcyclizine,homochlorcyclizine,,,homochlorcyclizine
408,atropine,atropine,CN1[C@H]2CC[C@@H]1C[C@@H](C2)OC(=O)[C@@H](CO)c...,BRD-K01825666-330-02-9,atropine
503,merck60,merck60,,,Merck60
600,ipratropium,ipratropium,CC(C)[N@@+]1(C)[C@H]2CC[C@@H]1C[C@@H](C2)OC(=O...,BRD-K01826778-004-06-9,ipratropium
655,alcuronium,alcuronium,OC\C=C1/C[N@+]2(CC=C)CC[C@@]34[C@@H]2C[C@@H]1\...,BRD-A84907376-300-03-8,alcuronium
739,ub-165,ub-165,"Clc1ccc(cn1)C1=CCC[C@H]2CC[C@@H]1N2 |&1:11,&2:...",BRD-A14574269-051-03-0,UB-165
797,deptropine,deptropine,CN1[C@H]2CC[C@@H]1C[C@@H](C2)OC1c2ccccc2CCc2cc...,BRD-K00005351-050-01-9,deptropine
1295,homatropine,homatropine,CN1[C@H]2CC[C@@H]1C[C@@H](C2)OC(=O)[C@@H](O)c1...,BRD-K01826529-004-11-9,homatropine
1382,zacopride,zacopride,COc1cc(N)c(Cl)cc1C(=O)N[C@H]1CN2CCC1CC2 |&1:13...,BRD-K01826799-003-03-9,zacopride
1567,estramustine,estramustine,,,estramustine
1606,psb-36,psb-36,[H][C@]12C[C@H]3C[C@]([H])(C[C@]3(C1)c1nc3n(CC...,BRD-K00004243-001-01-9,PSB-36
1693,clidinium,clidinium,C[N+]12CCC(CC1)[C@@H](C2)OC(=O)C(O)(c1ccccc1)c...,BRD-K01827265-004-09-9,clidinium
1749,bntx,bntx,,,BNTX
1755,homatropine-methylbromide,homatropine-methylbromide,C[N+]1(C)[C@H]2CC[C@@H]1C[C@@H](C2)OC(=O)[C@@H...,BRD-A54234250-004-02-9,homatropine-methylbromide
1766,sep-227900,sep-227900,,,SEP-227900
1777,3-cpmt,3-cpmt,CN1[C@H]2CC[C@@H]1C[C@@H](C2)O[C@H](c1ccccc1)c...,BRD-K00004217-003-01-9,3-CPMT
1793,doxorubicin,doxorubicin,,,doxorubicin
1807,pinitol,pinitol,,,pinitol
2198,s-nitrosoglutathione,s-nitrosoglutathione,,,S-nitrosoglutathione
2223,sb-218078,sb-218078,,,SB-218078

In [29]:
feature_files = {
    "MACCS": "perturbseqr_maccs_keys.csv",
    "CACTVS": "perturbseqr_cactvs_pubchem_fingerprints.csv",
    "Descriptors": "perturbseqr_molecular_descriptors.csv",
}

for label, filename in feature_files.items():
    df = pd.read_csv(Path.cwd() / filename, usecols=["record_id", "name"])
    print(label, df.shape, (df["record_id"] == morgan_metadata["record_id"]).all())

MACCS (6754, 2) True

In [30]:
for label, filename in feature_files.items():
    preview_df = pd.read_csv(Path.cwd() / filename, nrows=2)
    print(f"\n{label}")
    print("Shape:", preview_df.shape)
    print("First 15 columns:", preview_df.columns[:15].tolist())

MACCS
Shape: (2, 179)
First 15 columns: ['record_id', 'name', 'pubchem_cid', 'inchi_key', 'smiles', 'broad_id', 'moa', 'target', 'clinical_phase', 'disease_area', 'indication', 'fda_approved', 'maccs_0', 'maccs_1', 'maccs_2']

In [31]:
import csv

for label, filename in feature_files.items():
    with open(Path.cwd() / filename, "r", newline="") as f:
        header = next(csv.reader(f))

    print(f"\n{label}")
    print("Total columns:", len(header))
    print("First 15 columns:", header[:15])
    print("Last 10 columns:", header[-10:])

MACCS
Total columns: 179
First 15 columns: ['record_id', 'name', 'pubchem_cid', 'inchi_key', 'smiles', 'broad_id', 'moa', 'target', 'clinical_phase', 'disease_area', 'indication', 'fda_approved', 'maccs_0', 'maccs_1', 'maccs_2']
Last 10 columns: ['maccs_157', 'maccs_158', 'maccs_159', 'maccs_160', 'maccs_161', 'maccs_162', 'maccs_163', 'maccs_164', 'maccs_165', 'maccs_166']

CACTVS
Total columns: 893
First 15 columns: ['name', 'pubchem_cid', 'inchi_key', 'smiles', 'broad_id', 'moa', 'target', 'clinical_phase', 'disease_area', 'indication', 'fda_approved', 'cactvs_pubchem_fp', 'cactvs_0', 'cactvs_1', 'cactvs_2']
Last 10 columns: ['cactvs_871', 'cactvs_872', 'cactvs_873', 'cactvs_874', 'cactvs_875', 'cactvs_876', 'cactvs_877', 'cactvs_878', 'cactvs_879', 'cactvs_880']

Descriptors
Total columns: 21
First 15 columns: ['record_id', 'name', 'pubchem_cid', 'inchi_key', 'smiles', 'broad_id', 'moa', 'target', 'clinical_phase', 'disease_area', 'indication', 'fda_approved', 'molecular_weight', 'logP', 'TPSA']
Last 10 columns: ['fda_approved', 'molecular_weight', 'logP', 'TPSA', 'h_bond_donors', 'h_bond_acceptors', 'rotatable_bonds', 'aromatic_rings', 'heavy_atoms', 'formal_charge']

In [32]:
# Check whether matched names map uniquely to one SMILES string
matched_morgan_metadata.groupby("match_name")["smiles"].nunique().value_counts()

smiles
1    3131
Name: count, dtype: int64

In [33]:
model_index = matched_morgan_metadata[
    [
        "record_id",
        "perturbseqr_drug_id",
        "name",
        "match_name",
        "smiles",
        "broad_id",
        "signature_name",
        "moa",
        "target",
    ]
].copy()

model_index.to_csv(
    Path.cwd() / "part4_model_compound_index.csv",
    index=False
)

model_index.shape, model_index.head()

((3131, 9),
                 record_id     perturbseqr_drug_id                    name  \
 0                 be-2254                 be-2254                 be-2254
 1               dazmegrel               dazmegrel               dazmegrel
 2               nobiletin               nobiletin               nobiletin
 3                l-368899                l-368899                l-368899
 4  betamethasone-valerate  betamethasone-valerate  betamethasone-valerate

                match_name                                             smiles  \
 0                 be-2254            Oc1ccc(CCNC[C@H]2CCc3ccccc3C2=O)cc1 |r|
 1               dazmegrel                   Cc1c(Cn2ccnc2)c2ccccc2n1CCC(O)=O
 2               nobiletin  COc1ccc(cc1OC)-c1cc(=O)c2c(OC)c(OC)c(OC)c(OC)c2o1
 3                l-368899  Cc1ccccc1N1CCN(CC1)S(=O)(=O)C[C@]12CC[C@H](C[C...
 4  betamethasone-valerate  CCCCC(=O)O[C@@]1([C@@H](C)C[C@H]2[C@@H]3CCC4=C...

                  broad_id          signature_name  \
 0  BRD-A24429032-003-03-2                 BE-2254
 1  BRD-K20738689-001-01-2               dazmegrel
 2  BRD-K06753942-001-14-5               nobiletin
 3  BRD-K00004282-003-01-9                L-368899
 4  BRD-K34032314-001-04-1  betamethasone-valerate

                                moa             target
 0   adrenergic receptor antagonist             ADRA1A
 1   thromboxane synthase inhibitor             TBXAS1
 2                    MEK inhibitor             MAP2K1
 3     oxytocin receptor antagonist  AVPR1A|AVPR2|OXTR
 4  glucocorticoid receptor agonist              NR3C1  )

In [34]:
# Names we want from the consensus-signature file
wanted_signatures = set(model_index["signature_name"].str.lower().str.strip())

matched_signature_chunks = []

for chunk in pd.read_csv(
    consensus_path,
    sep="\t",
    compression="gzip",
    chunksize=500,
):
    chunk = chunk.rename(columns={chunk.columns[0]: "signature_name"})
    chunk["match_name"] = chunk["signature_name"].str.lower().str.strip()

    keep = chunk["match_name"].isin(wanted_signatures)
    if keep.any():
        matched_signature_chunks.append(chunk.loc[keep])

matched_signatures = pd.concat(matched_signature_chunks, ignore_index=True)

matched_signatures.shape

/var/folders/fn/ctr407bj6j96h5nhl6snwxqr0000gn/T/ipykernel_7622/3319732139.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chunk["match_name"] = chunk["signature_name"].str.lower().str.strip()

(3131, 12329)

In [35]:
matched_signatures[["signature_name", "match_name"]].head()

  signature_name match_name
0       afatinib   afatinib
1      erlotinib  erlotinib
2      neratinib  neratinib
3      lapatinib  lapatinib
4      pazopanib  pazopanib

In [37]:
matched_signatures.to_csv(
    Path.cwd() / "part4_matched_consensus_signatures.csv.gz",
    index=False,
    compression="gzip"
)

print("Saved compressed CSV target matrix.")

Saved compressed CSV target matrix.

In [1]:
# Inspect Novartis DRUG-seq DE summary

In [2]:
from pathlib import Path
import pandas as pd

Path.cwd()

PosixPath('data')

In [3]:
[p.name for p in Path.cwd().iterdir() if p.suffix == ".parquet"]

['nibr-drug-seq-de.parquet']

In [4]:
drugseq_summary_path = Path.cwd() / "nibr-drug-seq-de.parquet"

drugseq_summary = pd.read_parquet(drugseq_summary_path)

drugseq_summary.shape

(257671632, 3)

In [5]:
drugseq_summary.columns.tolist()

['pert_id', 'genes', 'logFC']

In [6]:
drugseq_summary.head(10)

                pert_id    genes     logFC
0  AF-80-QK39_0.01_24.0    COX5B  0.535137
1  AF-80-QK39_0.01_24.0     APRT  0.838632
2  AF-80-QK39_0.01_24.0     MCM4  1.658912
3  AF-80-QK39_0.01_24.0  NDUFA11  0.532010
4  AF-80-QK39_0.01_24.0      FAU  0.509526
5  AF-80-QK39_0.01_24.0  NDUFB11  0.604425
6  AF-80-QK39_0.01_24.0    RPLP2  0.334007
7  AF-80-QK39_0.01_24.0  RPL10P3  0.315489
8  AF-80-QK39_0.01_24.0   MT-CO3 -0.516769
9  AF-80-QK39_0.01_24.0   COX4I1  0.508100

In [7]:
unique_pert_ids = drugseq_summary["pert_id"].drop_duplicates()

print("Unique perturbation-condition IDs:", len(unique_pert_ids))
unique_pert_ids.head(20)

Unique perturbation-condition IDs: 17317

0         AF-80-QK39_0.01_24.0
14626     AF-18-FX20_0.01_24.0
29252     AA-51-RY00_0.01_24.0
43878     KF-70-DC09_0.01_24.0
58504     AC-55-CK61_0.01_24.0
73130     JF-74-GS02_0.01_24.0
87756     BC-45-VY95_0.01_24.0
102382    ME-14-LE68_0.01_24.0
117008    CC-14-WK34_0.01_24.0
131634    BC-55-CK01_0.01_24.0
146260    AD-23-AN14_0.01_24.0
160886    CB-12-HC20_0.01_24.0
175512    DD-23-QZ62_0.01_24.0
190138    CD-80-ZD47_0.01_24.0
204764    AF-33-AM86_0.01_24.0
219390    BE-82-MI84_0.01_24.0
234016    SF-52-LP14_0.01_24.0
248642    AD-12-YF12_0.01_24.0
263268    EA-86-QK08_0.01_24.0
277894    IA-95-KW09_0.01_24.0
Name: pert_id, dtype: str

In [8]:
pert_id_table = (
    unique_pert_ids
    .to_frame()
    .assign(
        nsn_code=lambda df: df["pert_id"].str.rsplit("_", n=2).str[0],
        dose=lambda df: df["pert_id"].str.rsplit("_", n=2).str[1],
        time_hours=lambda df: df["pert_id"].str.rsplit("_", n=2).str[2],
    )
)

pert_id_table.head()

                    pert_id    nsn_code  dose time_hours
0      AF-80-QK39_0.01_24.0  AF-80-QK39  0.01       24.0
14626  AF-18-FX20_0.01_24.0  AF-18-FX20  0.01       24.0
29252  AA-51-RY00_0.01_24.0  AA-51-RY00  0.01       24.0
43878  KF-70-DC09_0.01_24.0  KF-70-DC09  0.01       24.0
58504  AC-55-CK61_0.01_24.0  AC-55-CK61  0.01       24.0

In [9]:
print("Unique compound / NSN codes:", pert_id_table["nsn_code"].nunique())

pert_id_table["nsn_code"].value_counts().head(20)

Unique compound / NSN codes: 4330

nsn_code
AF-80-QK39    4
AF-18-FX20    4
AA-51-RY00    4
KF-70-DC09    4
AC-55-CK61    4
JF-74-GS02    4
BC-45-VY95    4
ME-14-LE68    4
CC-14-WK34    4
BC-55-CK01    4
AD-23-AN14    4
CB-12-HC20    4
DD-23-QZ62    4
CD-80-ZD47    4
AF-33-AM86    4
BE-82-MI84    4
SF-52-LP14    4
AD-12-YF12    4
EA-86-QK08    4
IA-95-KW09    4
Name: count, dtype: int64

In [10]:
pert_id_table["dose"].value_counts().sort_index()

dose
0.01    4329
0.1     4329
1.0     4329
10.0    4330
Name: count, dtype: int64

In [11]:
[p.name for p in Path.cwd().iterdir() if "drugseq" in p.name.lower() or "metadata" in p.name.lower()]

['DRUGseqr_metadata.tsv', 'perturbseqr_metadata']

In [12]:
drugseq_metadata_path = Path.cwd() / "DRUGseqr_metadata.tsv"

drugseq_metadata = pd.read_csv(drugseq_metadata_path, sep="\t")

drugseq_metadata.shape

(4262, 9)

In [13]:
drugseq_metadata.head()

,Unnamed: 0,inchi_key,smiles,cas_number,moa,target,title,name,cid
0,IF-72-BO18,IAASQMCXDRISAV-CYBMUJFWSA-N,O=C(N[C@H](Cc1ccccc1)C(=O)O)c1sc2cc(F)ccc2c1Cl,1279713-77-7,TLR3 gene inhibitor,['TLR3'],CU CPT 4a,(2R)-2-[(3-chloro-6-fluoro-1-benzothiophene-2-...,53242268.0
1,AA-44-BX20,BLQAXSAXSUNGMZ-UHFFFAOYSA-N,COc1ccc(-c2cnc(Nc3ccc(CCN4CCC(C(=O)O)CC4)cc3)n...,NaN,NaN,[],1-[2-[4-[[5-(4-Methoxyphenyl)pyrimidin-2-yl]am...,1-[2-[4-[[5-(4-methoxyphenyl)pyrimidin-2-yl]am...,16129187.0
2,DB-69-JG66,DRDIHUMOFDGYRJ-UHFFFAOYSA-N,CCN(CC)CCCNC(=O)Cn1nc(C)n2c(cc3sccc32)c1=O,NaN,NaN,[],N-[3-(diethylamino)propyl]-2-(12-methyl-9-oxid...,N-[3-(diethylamino)propyl]-2-(12-methyl-9-oxo-...,16011141.0
3,AB-16-LY07,PHVGLTMQBUFIQQ-UHFFFAOYSA-N,CNCCC=C1c2ccccc2CCc2ccccc21,203784-52-5,K(ir) 4.1 Blockers,['KCNJ10'],Nortriptyline,"N-methyl-3-(2-tricyclo[9.4.0.03,8]pentadeca-1(...",4543.0
4,GB-06-BA49,KILIYQSGUAKAHL-UHFFFAOYSA-N,Cc1cccc(-c2cc(-c3cncc(-c4ccc(C(C)N)cc4)c3)c3cc...,1171894-79-3,Activin receptor antagonist,['TGFBR1'],1-[4-[5-[6-(6-methylpyridin-2-yl)-1H-pyrrolo[2...,1-[4-[5-[6-(6-methylpyridin-2-yl)-1H-pyrrolo[2...,44195094.0

In [14]:
drugseq_metadata.columns.tolist()

['Unnamed: 0',
 'inchi_key',
 'smiles',
 'cas_number',
 'moa',
 'target',
 'title',
 'name',
 'cid']

In [15]:
drugseq_metadata = drugseq_metadata.rename(
    columns={"Unnamed: 0": "nsn_code"}
)

drugseq_metadata[["nsn_code", "name", "smiles", "title", "cid"]].head()

,nsn_code,name,smiles,title,cid
0,IF-72-BO18,(2R)-2-[(3-chloro-6-fluoro-1-benzothiophene-2-...,O=C(N[C@H](Cc1ccccc1)C(=O)O)c1sc2cc(F)ccc2c1Cl,CU CPT 4a,53242268.0
1,AA-44-BX20,1-[2-[4-[[5-(4-methoxyphenyl)pyrimidin-2-yl]am...,COc1ccc(-c2cnc(Nc3ccc(CCN4CCC(C(=O)O)CC4)cc3)n...,1-[2-[4-[[5-(4-Methoxyphenyl)pyrimidin-2-yl]am...,16129187.0
2,DB-69-JG66,N-[3-(diethylamino)propyl]-2-(12-methyl-9-oxo-...,CCN(CC)CCCNC(=O)Cn1nc(C)n2c(cc3sccc32)c1=O,N-[3-(diethylamino)propyl]-2-(12-methyl-9-oxid...,16011141.0
3,AB-16-LY07,"N-methyl-3-(2-tricyclo[9.4.0.03,8]pentadeca-1(...",CNCCC=C1c2ccccc2CCc2ccccc21,Nortriptyline,4543.0
4,GB-06-BA49,1-[4-[5-[6-(6-methylpyridin-2-yl)-1H-pyrrolo[2...,Cc1cccc(-c2cc(-c3cncc(-c4ccc(C(C)N)cc4)c3)c3cc...,1-[4-[5-[6-(6-methylpyridin-2-yl)-1H-pyrrolo[2...,44195094.0

In [16]:
print("Unique NSN codes in DE data:", pert_id_table["nsn_code"].nunique())
print("Unique NSN codes in metadata:", drugseq_metadata["nsn_code"].nunique())

drugseq_coverage = pert_id_table.merge(
    drugseq_metadata[
        ["nsn_code", "name", "smiles", "inchi_key", "moa", "target", "title", "cid"]
    ],
    on="nsn_code",
    how="left"
)

drugseq_coverage.shape

Unique NSN codes in DE data: 4330
Unique NSN codes in metadata: 4262

(17317, 11)

In [17]:
print("Missing SMILES:", drugseq_coverage["smiles"].isna().sum())
print("Missing names:", drugseq_coverage["name"].isna().sum())

drugseq_coverage.loc[
    drugseq_coverage["smiles"].isna(),
    ["nsn_code", "dose", "time_hours"]
].head(20)

Missing SMILES: 2261
Missing names: 2629

       nsn_code  dose time_hours
12   DD-23-QZ62  0.01       24.0
30   KA-75-LP02  0.01       24.0
91   BF-12-AC65  0.01       24.0
103  BA-15-LA22  0.01       24.0
145  ZD-27-QL96  0.01       24.0
165  WB-44-AA73  0.01       24.0
209  BD-11-DV28  10.0       24.0
225  CE-99-NH84  0.01       24.0
335  GA-68-SS47  0.01       24.0
341  FB-16-FK53  0.01       24.0
363  KA-73-PR92   0.1       24.0
375  CD-77-YB29   0.1       24.0
453  KB-56-XG08   0.1       24.0
463  CB-29-KG96   0.1       24.0
558  HC-76-HU27   0.1       24.0
569  HB-75-KT12   0.1       24.0
714  KA-73-PR92   1.0       24.0
726  CD-77-YB29   1.0       24.0
804  KB-56-XG08   1.0       24.0
814  CB-29-KG96   1.0       24.0

In [18]:
missing_structure_codes = drugseq_coverage.loc[
    drugseq_coverage["smiles"].isna(),
    "nsn_code"
].drop_duplicates()

print("Unique compound codes missing SMILES:", len(missing_structure_codes))
print(
    "Percent of unique DRUG-seq compounds missing SMILES:",
    round(100 * len(missing_structure_codes) / pert_id_table["nsn_code"].nunique(), 1),
    "%"
)

missing_structure_codes.head(20)

Unique compound codes missing SMILES: 566
Percent of unique DRUG-seq compounds missing SMILES: 13.1 %

12      DD-23-QZ62
30      KA-75-LP02
91      BF-12-AC65
103     BA-15-LA22
145     ZD-27-QL96
165     WB-44-AA73
209     BD-11-DV28
225     CE-99-NH84
335     GA-68-SS47
341     FB-16-FK53
363     KA-73-PR92
375     CD-77-YB29
453     KB-56-XG08
463     CB-29-KG96
558     HC-76-HU27
569     HB-75-KT12
1421    AE-00-DK14
1439    BE-08-QT65
1444    GD-11-LR18
1539    AB-09-JN93
Name: nsn_code, dtype: object

In [19]:
metadata_codes = set(drugseq_metadata["nsn_code"])

missing_from_metadata = [
    code for code in missing_structure_codes
    if code not in metadata_codes
]

print("Missing entirely from metadata:", len(missing_from_metadata))
print("Present in metadata but no SMILES:", len(missing_structure_codes) - len(missing_from_metadata))

Missing entirely from metadata: 68
Present in metadata but no SMILES: 498

In [20]:
drugseq_usable_compounds = (
    drugseq_coverage
    .dropna(subset=["smiles"])
    .drop_duplicates(subset=["nsn_code"])
    .sort_values("nsn_code")
    .reset_index(drop=True)
)

print(drugseq_usable_compounds.shape)

drugseq_usable_compounds[
    ["nsn_code", "name", "smiles", "dose", "time_hours", "moa", "target"]
].head()

(3764, 11)

,nsn_code,name,smiles,dose,time_hours,moa,target
0,AA-01-JO26,"2-amino-7-(thiophen-3-ylmethyl)-1,5-dihydropyr...",Nc1nc(O)c2[nH]cc(Cc3ccsc3)c2n1,0.01,24.0,Purine-Nucleoside Phosphorylase Inhibitors,['PNP']
1,AA-01-PS31,(4S)-8-[6-amino-5-(2-amino-3-chloropyridin-4-y...,Nc1nc(N2CCC3(CC2)COC[C@H]3N)cnc1Sc1ccnc(N)c1Cl,0.01,24.0,SHP2 allosteric inhibitor,['PTPN11']
2,AA-01-XV28,(1-oxo-2H-isoquinolin-5-yl) benzoate,O=C(Oc1cccc2c(O)nccc12)c1ccccc1,0.01,24.0,Poly(ADP-ribose)polymerase-2 (PARP-2) Inhibitors,['PARP2']
3,AA-02-FS13,benzylhydrazine,NNCc1ccccc1,0.01,24.0,NaN,[]
4,AA-03-QM41,NaN,Nc1ncnc2c1c(-c1cccc(OCc3ccccc3)c1)cn2[C@H]1C[C...,0.01,24.0,Angiogenesis Inhibitors;Inhibitors of Signal T...,['IGF1R']

In [21]:
drugseq_usable_compounds.to_csv(
    Path.cwd() / "drugseq_usable_compounds_with_smiles.csv",
    index=False
)

print("Saved:", Path.cwd() / "drugseq_usable_compounds_with_smiles.csv")

Saved: data/drugseq_usable_compounds_with_smiles.csv

In [22]:
print("Unique NSN codes:", drugseq_usable_compounds["nsn_code"].nunique())
print("Unique SMILES:", drugseq_usable_compounds["smiles"].nunique())
print(
    "Duplicate SMILES:",
    drugseq_usable_compounds["smiles"].duplicated().sum()
)

Unique NSN codes: 3764
Unique SMILES: 3763
Duplicate SMILES: 1

In [23]:
duplicate_smiles = (
    drugseq_usable_compounds.loc[
        drugseq_usable_compounds["smiles"].duplicated(keep=False),
        ["nsn_code", "name", "smiles", "title", "moa", "target"]
    ]
    .sort_values("smiles")
)

duplicate_smiles

,nsn_code,name,smiles,title,moa,target
220,AB-71-CI37,"(5R,5aR,8aR)-5-(3,4,5-trimethoxyphenyl)-5a,8,8...",COc1cc([C@@H]2c3cc4c(cc3C[C@H]3COC(=O)[C@@H]32...,Deoxypodophyllotoxin,Cyclooxygenase-2 Inhibitors;Angiogenesis Inhib...,['CASP3' 'PTGS2']
1139,CB-02-XL81,"(5R,5aR,8aR)-5-(3,4,5-trimethoxyphenyl)-5a,8,8...",COc1cc([C@@H]2c3cc4c(cc3C[C@H]3COC(=O)[C@@H]32...,Deoxypodophyllotoxin,Cyclooxygenase-2 Inhibitors;Angiogenesis Inhib...,['CASP3' 'PTGS2']

In [26]:
# Existing 6,801-compound registry
drug_master_df = pd.DataFrame.from_dict(drug_master, orient="index")
drug_master_df.index.name = "perturbseqr_drug_id"
drug_master_df = drug_master_df.reset_index()

# Keep the key chemical identifiers
existing_registry = drug_master_df[
    ["perturbseqr_drug_id", "name", "smiles", "inchi_key", "broad_id"]
].copy()

# Check overlap using InChIKey
drugseq_with_registry_flag = drugseq_usable_compounds.merge(
    existing_registry,
    on="inchi_key",
    how="left",
    suffixes=("_drugseq", "_existing")
)

print("DRUG-seq usable compounds:", len(drugseq_with_registry_flag))
print(
    "Already in existing registry:",
    drugseq_with_registry_flag["perturbseqr_drug_id"].notna().sum()
)
print(
    "New compounds not in existing registry:",
    drugseq_with_registry_flag["perturbseqr_drug_id"].isna().sum()
)

DRUG-seq usable compounds: 3771
Already in existing registry: 1133
New compounds not in existing registry: 2638

In [25]:
import json
import pandas as pd
from pathlib import Path

drug_master_path = Path.cwd() / "drug_master.json"

with open(drug_master_path, "r") as f:
    drug_master = json.load(f)

len(drug_master)

6801

In [27]:
drugseq_with_registry_flag.loc[
    drugseq_with_registry_flag["perturbseqr_drug_id"].notna(),
    ["nsn_code", "name_drugseq", "name_existing", "smiles_drugseq"]
].head()

,nsn_code,name_drugseq,name_existing,smiles_drugseq
4,AA-03-QM41,NaN,nvp-adw742,Nc1ncnc2c1c(-c1cccc(OCc3ccccc3)c1)cn2[C@H]1C[C...
5,AA-07-BW60,4-chloro-N-(2-morpholin-4-ylethyl)benzamide,moclobemide,O=C(NCCN1CCOCC1)c1ccc(Cl)cc1
6,AA-07-FZ97,"(1R,3S,5Z)-5-[(2E)-2-[(1R,3aS,7aR)-1-[(2R)-6-h...",calcitriol,C=C1/C(=C\\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)CCCC...
7,AA-09-HG96,"3,7-dimethyl-1-(5-oxohexyl)purine-2,6-dione",pentoxifylline,CC(=O)CCCCn1c(=O)c2c(ncn2C)n(C)c1=O
9,AA-10-VR76,"3,4,6-trichloro-2-[(2,3,5-trichloro-6-hydroxyp...",hexachlorophene,Oc1c(Cl)cc(Cl)c(Cl)c1Cc1c(O)c(Cl)cc(Cl)c1Cl

In [28]:
drugseq_with_registry_flag.loc[
    drugseq_with_registry_flag["perturbseqr_drug_id"].isna(),
    ["nsn_code", "name_drugseq", "smiles_drugseq", "inchi_key"]
].head()

,nsn_code,name_drugseq,smiles_drugseq,inchi_key
0,AA-01-JO26,"2-amino-7-(thiophen-3-ylmethyl)-1,5-dihydropyr...",Nc1nc(O)c2[nH]cc(Cc3ccsc3)c2n1,QDPMHXUWMPNTEQ-UHFFFAOYSA-N
1,AA-01-PS31,(4S)-8-[6-amino-5-(2-amino-3-chloropyridin-4-y...,Nc1nc(N2CCC3(CC2)COC[C@H]3N)cnc1Sc1ccnc(N)c1Cl,OMJHHTRDBKAMSN-LLVKDONJSA-N
2,AA-01-XV28,(1-oxo-2H-isoquinolin-5-yl) benzoate,O=C(Oc1cccc2c(O)nccc12)c1ccccc1,FFWUPFYTTMMSTH-UHFFFAOYSA-N
3,AA-02-FS13,benzylhydrazine,NNCc1ccccc1,NHOWLEZFTHYCTP-UHFFFAOYSA-N
8,AA-10-BH32,"(2S)-N-[(1S)-2-[(3aR,7aS)-7-oxo-6-(2-phenyleth...",CN[C@@H](C)C(=O)N[C@H](C(=O)N1CC[C@H]2CCN(CCc3...,KOEJPVOFYIFFSM-UQAQOTMJSA-N

In [29]:
# Make the existing registry one row per InChIKey
existing_registry_unique = (
    existing_registry
    .dropna(subset=["inchi_key"])
    .drop_duplicates(subset=["inchi_key"])
)

existing_inchi_keys = set(existing_registry_unique["inchi_key"])

drugseq_registry_status = drugseq_usable_compounds.copy()
drugseq_registry_status["already_in_existing_registry"] = (
    drugseq_registry_status["inchi_key"].isin(existing_inchi_keys)
)

print("Usable DRUG-seq compounds:", len(drugseq_registry_status))
print(
    "Already represented in the 6,801 registry:",
    drugseq_registry_status["already_in_existing_registry"].sum()
)
print(
    "New DRUG-seq compounds to add:",
    (~drugseq_registry_status["already_in_existing_registry"]).sum()
)

Usable DRUG-seq compounds: 3764
Already represented in the 6,801 registry: 1126
New DRUG-seq compounds to add: 2638

In [30]:
drugseq_registry_status.loc[
    drugseq_registry_status["already_in_existing_registry"],
    ["nsn_code", "name", "smiles", "inchi_key"]
].head()

,nsn_code,name,smiles,inchi_key
4,AA-03-QM41,NaN,Nc1ncnc2c1c(-c1cccc(OCc3ccccc3)c1)cn2[C@H]1C[C...,LSFLAQVDISHMNB-AFARHQOCSA-N
5,AA-07-BW60,4-chloro-N-(2-morpholin-4-ylethyl)benzamide,O=C(NCCN1CCOCC1)c1ccc(Cl)cc1,YHXISWVBGDMDLQ-UHFFFAOYSA-N
6,AA-07-FZ97,"(1R,3S,5Z)-5-[(2E)-2-[(1R,3aS,7aR)-1-[(2R)-6-h...",C=C1/C(=C\\C=C2/CCC[C@]3(C)[C@@H]([C@H](C)CCCC...,GMRQFYUYWCNGIN-NKMMMXOESA-N
7,AA-09-HG96,"3,7-dimethyl-1-(5-oxohexyl)purine-2,6-dione",CC(=O)CCCCn1c(=O)c2c(ncn2C)n(C)c1=O,BYPFEZZEUUWMEJ-UHFFFAOYSA-N
9,AA-10-VR76,"3,4,6-trichloro-2-[(2,3,5-trichloro-6-hydroxyp...",Oc1c(Cl)cc(Cl)c(Cl)c1Cc1c(O)c(Cl)cc(Cl)c1Cl,ACGUYXCXAPNIKK-UHFFFAOYSA-N

In [31]:
drugseq_registry_status.loc[
    ~drugseq_registry_status["already_in_existing_registry"],
    ["nsn_code", "name", "smiles", "inchi_key"]
].head()

,nsn_code,name,smiles,inchi_key
0,AA-01-JO26,"2-amino-7-(thiophen-3-ylmethyl)-1,5-dihydropyr...",Nc1nc(O)c2[nH]cc(Cc3ccsc3)c2n1,QDPMHXUWMPNTEQ-UHFFFAOYSA-N
1,AA-01-PS31,(4S)-8-[6-amino-5-(2-amino-3-chloropyridin-4-y...,Nc1nc(N2CCC3(CC2)COC[C@H]3N)cnc1Sc1ccnc(N)c1Cl,OMJHHTRDBKAMSN-LLVKDONJSA-N
2,AA-01-XV28,(1-oxo-2H-isoquinolin-5-yl) benzoate,O=C(Oc1cccc2c(O)nccc12)c1ccccc1,FFWUPFYTTMMSTH-UHFFFAOYSA-N
3,AA-02-FS13,benzylhydrazine,NNCc1ccccc1,NHOWLEZFTHYCTP-UHFFFAOYSA-N
8,AA-10-BH32,"(2S)-N-[(1S)-2-[(3aR,7aS)-7-oxo-6-(2-phenyleth...",CN[C@@H](C)C(=O)N[C@H](C(=O)N1CC[C@H]2CCN(CCc3...,KOEJPVOFYIFFSM-UQAQOTMJSA-N

In [32]:
drugseq_registry_status.to_csv(
    Path.cwd() / "drugseq_registry_overlap_status.csv",
    index=False
)

print("Saved DRUG-seq registry-overlap table.")

Saved DRUG-seq registry-overlap table.

In [33]:
drugseq_new_compounds = drugseq_registry_status.loc[
    ~drugseq_registry_status["already_in_existing_registry"]
].copy()

drugseq_new_compounds.to_csv(
    Path.cwd() / "drugseq_new_compounds_with_smiles.csv",
    index=False
)

print(drugseq_new_compounds.shape)

(2638, 12)

In [34]:
# Inspect Tahoe 100M metadata

In [35]:
[p.name for p in Path.cwd().iterdir() if "metadata" in p.name.lower()]

['drug_metadata.parquet', 'DRUGseqr_metadata.tsv', 'perturbseqr_metadata']

In [36]:
tahoe_drug_path = Path.cwd() / "drug_metadata.parquet"

tahoe_drugs = pd.read_parquet(tahoe_drug_path)

tahoe_drugs.shape

(379, 9)

In [37]:
tahoe_drugs.head()

,drug,targets,moa-broad,moa-fine,human-approved,clinical-trials,gpt-notes-approval,canonical_smiles,pubchem_cid
0,Talc,NaN,unclear,unclear,yes,yes,Talc used in pharma and cosmetics; safety unde...,[OH-].[OH-].[O-][Si]12O[Si]3(O[Si](O1)(O[Si](O...,165411828.0
1,Bortezomib,PSMB5,inhibitor/antagonist,Proteasome inhibitor,yes,yes,Approved for multiple myeloma and mantle cell ...,B(C(CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C2=NC=CN...,387447.0
2,Ixazomib,PSMB5,inhibitor/antagonist,Proteasome inhibitor,yes,yes,Approved for multiple myeloma treatment.,B(C(CC(C)C)NC(=O)CNC(=O)C1=C(C=CC(=C1)Cl)Cl)(O)O,25183872.0
3,Ixazomib citrate,"PSMB1, PSMB2, PSMB5",inhibitor/antagonist,Proteasome inhibitor,yes,yes,Approved for multiple myeloma treatment as par...,B1(OC(=O)C(O1)(CC(=O)O)CC(=O)O)C(CC(C)C)NC(=O)...,56844015.0
4,Lactate (calcium),NaN,unclear,unclear,yes,yes,"Used in medical settings, but not specifically...",C.CC(C(=O)[O-])O.[Ca+2],168311648.0

In [38]:
tahoe_drugs.columns.tolist()

['drug',
 'targets',
 'moa-broad',
 'moa-fine',
 'human-approved',
 'clinical-trials',
 'gpt-notes-approval',
 'canonical_smiles',
 'pubchem_cid']

In [39]:
tahoe_compounds = tahoe_drugs[
    ["drug", "canonical_smiles", "pubchem_cid", "targets", "moa-broad", "moa-fine"]
].copy()

tahoe_compounds = tahoe_compounds.rename(
    columns={
        "canonical_smiles": "smiles",
        "moa-broad": "moa_broad",
        "moa-fine": "moa_fine",
    }
)

print("Tahoe compounds:", len(tahoe_compounds))
print("Missing SMILES:", tahoe_compounds["smiles"].isna().sum())
print("Unique SMILES:", tahoe_compounds["smiles"].nunique())

tahoe_compounds.head()

Tahoe compounds: 379
Missing SMILES: 2
Unique SMILES: 375

,drug,smiles,pubchem_cid,targets,moa_broad,moa_fine
0,Talc,[OH-].[OH-].[O-][Si]12O[Si]3(O[Si](O1)(O[Si](O...,165411828.0,NaN,unclear,unclear
1,Bortezomib,B(C(CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C2=NC=CN...,387447.0,PSMB5,inhibitor/antagonist,Proteasome inhibitor
2,Ixazomib,B(C(CC(C)C)NC(=O)CNC(=O)C1=C(C=CC(=C1)Cl)Cl)(O)O,25183872.0,PSMB5,inhibitor/antagonist,Proteasome inhibitor
3,Ixazomib citrate,B1(OC(=O)C(O1)(CC(=O)O)CC(=O)O)C(CC(C)C)NC(=O)...,56844015.0,"PSMB1, PSMB2, PSMB5",inhibitor/antagonist,Proteasome inhibitor
4,Lactate (calcium),C.CC(C(=O)[O-])O.[Ca+2],168311648.0,NaN,unclear,unclear

In [40]:
tahoe_compounds.to_csv(
    Path.cwd() / "tahoe_compounds_with_smiles.csv",
    index=False
)

In [41]:
tahoe_compounds.loc[
    tahoe_compounds["smiles"].isna(),
    ["drug", "pubchem_cid", "targets", "moa_broad", "moa_fine"]
]

                     drug  pubchem_cid targets             moa_broad moa_fine
372  Sacubitril/Valsartan          NaN   AGTR1  inhibitor/antagonist  unclear
374           Verteporfin          NaN    YAP1  inhibitor/antagonist  unclear

In [42]:
from rdkit import Chem

def canonicalize_smiles(smiles):
    if pd.isna(smiles):
        return None
    
    mol = Chem.MolFromSmiles(smiles)
    return Chem.MolToSmiles(mol) if mol is not None else None

tahoe_compounds["canonical_smiles"] = tahoe_compounds["smiles"].apply(canonicalize_smiles)

print("Valid canonical Tahoe SMILES:", tahoe_compounds["canonical_smiles"].notna().sum())
print("Invalid/unreadable Tahoe SMILES:", tahoe_compounds["canonical_smiles"].isna().sum())

Valid canonical Tahoe SMILES: 377
Invalid/unreadable Tahoe SMILES: 2

In [43]:
# Canonicalize existing registry SMILES
existing_registry["canonical_smiles"] = existing_registry["smiles"].apply(
    canonicalize_smiles
)

# Canonicalize DRUG-seq SMILES
drugseq_usable_compounds["canonical_smiles"] = (
    drugseq_usable_compounds["smiles"].apply(canonicalize_smiles)
)

# Make sets of structures already represented
existing_smiles = set(
    existing_registry["canonical_smiles"].dropna()
)

drugseq_smiles = set(
    drugseq_usable_compounds["canonical_smiles"].dropna()
)

# Label Tahoe coverage
tahoe_registry_status = tahoe_compounds.copy()

tahoe_registry_status["in_existing_registry"] = (
    tahoe_registry_status["canonical_smiles"].isin(existing_smiles)
)

tahoe_registry_status["in_drugseq"] = (
    tahoe_registry_status["canonical_smiles"].isin(drugseq_smiles)
)

tahoe_registry_status["new_to_both"] = (
    tahoe_registry_status["canonical_smiles"].notna()
    & ~tahoe_registry_status["in_existing_registry"]
    & ~tahoe_registry_status["in_drugseq"]
)

print("Tahoe compounds with valid structures:",
      tahoe_registry_status["canonical_smiles"].notna().sum())

print("Already in existing 6,801 registry:",
      tahoe_registry_status["in_existing_registry"].sum())

print("Already in DRUG-seq:",
      tahoe_registry_status["in_drugseq"].sum())

print("New to both:",
      tahoe_registry_status["new_to_both"].sum())

[18:39:28] SMILES Parse Error: syntax error while parsing: C[C@@H]1C[C@H](C)C[C@H](C)[C@@H](O)CC(=O)O[C@H]([C@@H]2CCC[C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@@H](C)C1
[18:39:28] SMILES Parse Error: check for mistakes around position 80:
[18:39:28] C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@
[18:39:28] ~~~~~~~~~~~~~~~~~~~~^
[18:39:28] SMILES Parse Error: Failed parsing SMILES 'C[C@@H]1C[C@H](C)C[C@H](C)[C@@H](O)CC(=O)O[C@H]([C@@H]2CCC[C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@@H](C)C1' for input: 'C[C@@H]1C[C@H](C)C[C@H](C)[C@@H](O)CC(=O)O[C@H]([C@@H]2CCC[C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@@H](C)C1'

Tahoe compounds with valid structures: 377
Already in existing 6,801 registry: 106
Already in DRUG-seq: 49
New to both: 262

In [44]:
tahoe_registry_status.loc[
    tahoe_registry_status["new_to_both"],
    ["drug", "smiles", "pubchem_cid", "targets", "moa_broad"]
].head(20)

,drug,smiles,pubchem_cid,targets,moa_broad
0,Talc,[OH-].[OH-].[O-][Si]12O[Si]3(O[Si](O1)(O[Si](O...,165411828.0,NaN,unclear
1,Bortezomib,B(C(CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C2=NC=CN...,387447.0,PSMB5,inhibitor/antagonist
2,Ixazomib,B(C(CC(C)C)NC(=O)CNC(=O)C1=C(C=CC(=C1)Cl)Cl)(O)O,25183872.0,PSMB5,inhibitor/antagonist
3,Ixazomib citrate,B1(OC(=O)C(O1)(CC(=O)O)CC(=O)O)C(CC(C)C)NC(=O)...,56844015.0,"PSMB1, PSMB2, PSMB5",inhibitor/antagonist
4,Lactate (calcium),C.CC(C(=O)[O-])O.[Ca+2],168311648.0,NaN,unclear
5,Bisoprolol (hemifumarate),C.CC(C)NCC(COC1=CC=C(C=C1)COCCOC(C)C)O.C(=CC(=...,168312271.0,ADRB1,inhibitor/antagonist
6,Fumaric acid,C(=CC(=O)O)C(=O)O,444972.0,NaN,inhibitor/antagonist
8,L-Eflornithine (monohydrochloride),C(CC(C(F)F)(C(=O)O)N)CN.Cl,16048568.0,ODC1,inhibitor/antagonist
9,Cysteamine (hydrochloride),C(CS)N.Cl,9082.0,NaN,unclear
10,Darinaparsin,C[As](C)SCC(C(=O)NCC(=O)O)NC(=O)CCC(C(=O)O)N,11683005.0,NaN,unclear
11,Entecavir (monohydrate),C=C1C(CC(C1CO)O)N2C=NC3=C2N=C(NC3=O)N.O,135526609.0,NaN,unclear
12,Allantoin,C1(C(=O)NC(=O)N1)NC(=O)N,204.0,NaN,unclear
14,L-Thyroxine (sodium salt pentahydrate),C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,23665037.0,NaN,unclear
16,Gallic acid (hydrate),C1=C(C=C(C(=C1O)O)O)C(=O)O.O,24721416.0,NaN,inhibitor/antagonist
17,ERK5-IN-2,C1=CC(=C(C(=C1)Br)C(=O)C2=CNC(=C2)C(=O)NC3=CN=...,118959080.0,MAPK7,inhibitor/antagonist
18,Vilanterol,C1=CC(=C(C(=C1)Cl)COCCOCCCCCCNCC(C2=CC(=C(C=C2...,10184665.0,ADRB2,activator/agonist
19,Niclosamide (olamine),C1=CC(=C(C=C1[N+](=O)[O-])Cl)NC(=O)C2=C(C=CC(=...,14992.0,STAT3,inhibitor/antagonist
20,Norepinephrine (hydrochloride),C1=CC(=C(C=C1C(CN)O)O)O.Cl,11672905.0,"ADRA1A, ADRA1B, ADRA1D, ADRA2A, ADRA2B, ADRA2C...",activator/agonist
22,Mitoxantrone (dihydrochloride),C1=CC(=C2C(=C1NCCNCCO)C(=O)C3=C(C=CC(=C3C2=O)O...,51082.0,"TOP2A, TOP2B, PRKCA",inhibitor/antagonist
23,Pentamidine (isethionate),C1=CC(=CC=C1C(=N)N)OCCCCCOC2=CC=C(C=C2)C(=N)N....,8813.0,PRLR,inhibitor/antagonist

In [45]:
tahoe_registry_status.to_csv(
    Path.cwd() / "tahoe_registry_overlap_status.csv",
    index=False
)

tahoe_new_compounds = tahoe_registry_status.loc[
    tahoe_registry_status["new_to_both"]
].copy()

tahoe_new_compounds.to_csv(
    Path.cwd() / "tahoe_new_compounds_with_smiles.csv",
    index=False
)

print(tahoe_new_compounds.shape)

(262, 10)

In [46]:
# Build expanded compound structure registry

In [47]:
# Keep only existing-registry compounds with usable canonical SMILES
existing_for_registry = existing_registry[
    existing_registry["canonical_smiles"].notna()
].copy()

existing_for_registry = existing_for_registry.rename(
    columns={
        "name": "compound_name",
        "smiles": "original_smiles",
    }
)

existing_for_registry["source_existing_registry"] = True
existing_for_registry["source_drugseq"] = False
existing_for_registry["source_tahoe"] = False

In [50]:
# Add canonical SMILES to the DRUG-seq overlap/status table
drugseq_registry_status = drugseq_registry_status.copy()

drugseq_registry_status["canonical_smiles"] = (
    drugseq_registry_status["smiles"].apply(canonicalize_smiles)
)

# Keep only compounds with readable structures
drugseq_for_registry = drugseq_registry_status[
    drugseq_registry_status["canonical_smiles"].notna()
].copy()

# Rename columns to match the shared expanded-registry format
drugseq_for_registry = drugseq_for_registry.rename(
    columns={
        "name": "compound_name",
        "smiles": "original_smiles",
    }
)

# Source flags
drugseq_for_registry["source_existing_registry"] = (
    drugseq_for_registry["already_in_existing_registry"]
)

drugseq_for_registry["source_drugseq"] = True
drugseq_for_registry["source_tahoe"] = False

# Preview only the columns we will eventually combine
drugseq_for_registry[
    [
        "compound_name",
        "original_smiles",
        "canonical_smiles",
        "source_existing_registry",
        "source_drugseq",
        "source_tahoe",
    ]
].head()

[18:44:19] SMILES Parse Error: syntax error while parsing: C[C@@H]1C[C@H](C)C[C@H](C)[C@@H](O)CC(=O)O[C@H]([C@@H]2CCC[C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@@H](C)C1
[18:44:19] SMILES Parse Error: check for mistakes around position 80:
[18:44:19] C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@
[18:44:19] ~~~~~~~~~~~~~~~~~~~~^
[18:44:19] SMILES Parse Error: Failed parsing SMILES 'C[C@@H]1C[C@H](C)C[C@H](C)[C@@H](O)CC(=O)O[C@H]([C@@H]2CCC[C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@@H](C)C1' for input: 'C[C@@H]1C[C@H](C)C[C@H](C)[C@@H](O)CC(=O)O[C@H]([C@@H]2CCC[C@H]2C(=O)O)C/C=C\\\\C=C(/C#N)[C@H](O)[C@@H](C)C1'

,compound_name,original_smiles,canonical_smiles,source_existing_registry,source_drugseq,source_tahoe
0,"2-amino-7-(thiophen-3-ylmethyl)-1,5-dihydropyr...",Nc1nc(O)c2[nH]cc(Cc3ccsc3)c2n1,Nc1nc(O)c2[nH]cc(Cc3ccsc3)c2n1,False,True,False
1,(4S)-8-[6-amino-5-(2-amino-3-chloropyridin-4-y...,Nc1nc(N2CCC3(CC2)COC[C@H]3N)cnc1Sc1ccnc(N)c1Cl,Nc1nc(N2CCC3(CC2)COC[C@H]3N)cnc1Sc1ccnc(N)c1Cl,False,True,False
2,(1-oxo-2H-isoquinolin-5-yl) benzoate,O=C(Oc1cccc2c(O)nccc12)c1ccccc1,O=C(Oc1cccc2c(O)nccc12)c1ccccc1,False,True,False
3,benzylhydrazine,NNCc1ccccc1,NNCc1ccccc1,False,True,False
4,NaN,Nc1ncnc2c1c(-c1cccc(OCc3ccccc3)c1)cn2[C@H]1C[C...,Nc1ncnc2c1c(-c1cccc(OCc3ccccc3)c1)cn2[C@H]1C[C...,True,True,False

In [51]:
# Keep Tahoe compounds with usable canonical SMILES
tahoe_for_registry = tahoe_registry_status[
    tahoe_registry_status["canonical_smiles"].notna()
].copy()

tahoe_for_registry = tahoe_for_registry.rename(
    columns={
        "drug": "compound_name",
        "smiles": "original_smiles",
    }
)

tahoe_for_registry["source_existing_registry"] = (
    tahoe_for_registry["in_existing_registry"]
)

tahoe_for_registry["source_drugseq"] = tahoe_for_registry["in_drugseq"]
tahoe_for_registry["source_tahoe"] = True

tahoe_for_registry[
    [
        "compound_name",
        "original_smiles",
        "canonical_smiles",
        "source_existing_registry",
        "source_drugseq",
        "source_tahoe",
    ]
].head()

,compound_name,original_smiles,canonical_smiles,source_existing_registry,source_drugseq,source_tahoe
0,Talc,[OH-].[OH-].[O-][Si]12O[Si]3(O[Si](O1)(O[Si](O...,[Mg+2].[Mg+2].[Mg+2].[O-][Si]12O[Si]3([O-])O[S...,False,False,True
1,Bortezomib,B(C(CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C2=NC=CN...,CC(C)CC(NC(=O)C(Cc1ccccc1)NC(=O)c1cnccn1)B(O)O,False,False,True
2,Ixazomib,B(C(CC(C)C)NC(=O)CNC(=O)C1=C(C=CC(=C1)Cl)Cl)(O)O,CC(C)CC(NC(=O)CNC(=O)c1cc(Cl)ccc1Cl)B(O)O,False,False,True
3,Ixazomib citrate,B1(OC(=O)C(O1)(CC(=O)O)CC(=O)O)C(CC(C)C)NC(=O)...,CC(C)CC(NC(=O)CNC(=O)c1cc(Cl)ccc1Cl)B1OC(=O)C(...,False,False,True
4,Lactate (calcium),C.CC(C(=O)[O-])O.[Ca+2],C.CC(O)C(=O)[O-].[Ca+2],False,False,True

In [52]:
registry_columns = [
    "compound_name",
    "original_smiles",
    "canonical_smiles",
    "source_existing_registry",
    "source_drugseq",
    "source_tahoe",
]

expanded_registry_raw = pd.concat(
    [
        existing_for_registry[registry_columns],
        drugseq_for_registry[registry_columns],
        tahoe_for_registry[registry_columns],
    ],
    ignore_index=True,
)

print("Rows before removing duplicate structures:", len(expanded_registry_raw))
expanded_registry_raw.head()

Rows before removing duplicate structures: 10919

,compound_name,original_smiles,canonical_smiles,source_existing_registry,source_drugseq,source_tahoe
0,be-2254,Oc1ccc(CCNC[C@H]2CCc3ccccc3C2=O)cc1 |r|,O=C1c2ccccc2CC[C@@H]1CNCCc1ccc(O)cc1,True,False,False
1,tasimelteon,CCC(=O)NC[C@@H]1C[C@H]1c1cccc2OCCc12,CCC(=O)NC[C@@H]1C[C@H]1c1cccc2c1CCO2,True,False,False
2,esaxerenone,Cc1c(cn(CCO)c1-c1ccccc1C(F)(F)F)C(=O)Nc1ccc(cc...,Cc1c(C(=O)Nc2ccc(S(C)(=O)=O)cc2)cn(CCO)c1-c1cc...,True,False,False
3,ixazomib-citrate,CC(C)C[C@H](NC(=O)CNC(=O)c1cc(Cl)ccc1Cl)B1OC(=...,CC(C)C[C@H](NC(=O)CNC(=O)c1cc(Cl)ccc1Cl)B1OC(=...,True,False,False
4,alendronate,NCCCC(O)(P(O)(O)=O)P(O)(O)=O,NCCCC(O)(P(=O)(O)O)P(=O)(O)O,True,False,False

In [53]:
expanded_registry = (
    expanded_registry_raw
    .groupby("canonical_smiles", as_index=False)
    .agg(
        compound_name=("compound_name", "first"),
        original_smiles=("original_smiles", "first"),
        source_existing_registry=("source_existing_registry", "max"),
        source_drugseq=("source_drugseq", "max"),
        source_tahoe=("source_tahoe", "max"),
    )
)

print("Unique structures in expanded registry:", len(expanded_registry))
print("Present in original registry:", expanded_registry["source_existing_registry"].sum())
print("Present in DRUG-seq:", expanded_registry["source_drugseq"].sum())
print("Present in Tahoe:", expanded_registry["source_tahoe"].sum())

expanded_registry.head()

Unique structures in expanded registry: 9668
Present in original registry: 6786
Present in DRUG-seq: 3762
Present in Tahoe: 374

,canonical_smiles,compound_name,original_smiles,source_existing_registry,source_drugseq,source_tahoe
0,,terreic-acid-(-),,True,False,False
1,Br.CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21,Citalopram (hydrobromide),CN(C)CCCC1(C2=C(CO1)C=C(C=C2)C#N)C3=CC=C(C=C3)...,False,False,True
2,BrC1C(Br)C(Br)C(Br)C(Br)C1Br,"1,2,3,4,5,6-hexabromocyclohexane",BrC1C(Br)C(Br)C(Br)C(Br)C1Br,True,False,False
3,Brc1c(Br)c(Br)c2n[nH]nc2c1Br,"4,5,6,7-tetrabromobenzotriazole",Brc1c(Br)c(Br)c2n[nH]nc2c1Br,True,False,False
4,Brc1c(NC2=NCCN2)ccc2nccnc12,brimonidine,Brc1c(NC2=NCCN2)ccc2nccnc12 |t:4|,True,False,True

In [54]:
expanded_registry.to_csv(
    Path.cwd() / "expanded_compound_structure_registry.csv",
    index=False
)

print("Saved expanded registry.")

Saved expanded registry.